sudo: false
language: go
go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.9
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=crypto.coverprofile
  - goveralls -coverprofile=crypto.coverprofile -service=travis-ci
