sudo: false
language: go
go:
  - 1.8
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=crypto.coverprofile
  - goveralls -coverprofile=crypto.coverprofile -service=travis-ci
